# Generated by Django 5.0 on 2025-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enregistrement_utilisateuretendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='enregistrement',
            name='ville',
            field=models.CharField(blank=True, choices=[('Kinshasa', 'Kinshasa'), ('Lubumbashi', 'Lubumbashi'), ('Goma', 'Goma'), ('Bukavu', 'Bukavu'), ('Kisangani', 'Kisangani'), ('Matadi', 'Matadi'), ('Mbuji-Mayi', 'Mbuji-Mayi'), ('Kananga', 'Kananga'), ('Beni', 'Beni'), ('Likasi', 'Likasi'), ('Kolwezi', 'Kolwezi')], max_length=50, null=True),
        ),
    ]
