# Generated by Django 5.0 on 2025-06-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enregistrement_sexe_enregistrement_ville'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enregistrement',
        ),
    ]
