# Generated by Django 5.0 on 2025-06-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure',
        ),
        migrations.CreateModel(
            name='EvenementDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='core.evenement')),
            ],
        ),
    ]
