# Generated by Django 5.0 on 2025-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_evenement_date_remove_evenement_heure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caroussel/')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
