# Generated by Django 5.0 on 2025-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_fichier_alter_carousselimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='approuve',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
