# Generated by Django 5.0 on 2025-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_temoignage_approuve_alter_temoignage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/medias/intervenants/')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='intervenants',
            field=models.ManyToManyField(blank=True, related_name='evenements', to='core.intervenant'),
        ),
    ]
