# Generated by Django 5.0 on 2025-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_intervenant_evenement_intervenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='intervenants',
        ),
        migrations.AddField(
            model_name='evenement',
            name='affiche_evenement',
            field=models.ImageField(blank=True, null=True, upload_to='static/medias/affiches/'),
        ),
    ]
