# Generated by Django 5.0 on 2025-06-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_evenement_intervenants_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervenant',
        ),
    ]
