# Generated by Django 5.0 on 2025-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_intervenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='affiche_evenement',
            field=models.ImageField(blank=True, null=True, upload_to='affiches/'),
        ),
    ]
