# Generated by Django 5.0 on 2025-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_carousselimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/medias/pdfs/', verbose_name='PDF associé'),
        ),
    ]
