# Generated by Django 5.0 on 2025-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_video_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image pour le slider principal', upload_to='slider/')),
                ('image_webp', models.ImageField(blank=True, help_text="Version WebP de l'image (optionnelle, sera générée automatiquement)", null=True, upload_to='slider/')),
                ('titre', models.CharField(max_length=100)),
                ('sous_titre', models.CharField(max_length=200)),
                ('texte_bouton', models.CharField(default='En savoir plus', max_length=50)),
                ('url_bouton', models.CharField(default='#', max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage des slides")),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image du slider',
                'verbose_name_plural': 'Images du slider',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
