# Generated by Django 5.0 on 2025-07-14 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('titre', models.CharField(help_text="Titre ou fonction de l'animateur", max_length=200)),
                ('bio', models.TextField(blank=True, help_text="Courte biographie de l'animateur")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animateurs/')),
            ],
            options={
                'verbose_name': 'Animateur',
                'verbose_name_plural': 'Animateurs',
            },
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème du MasterClass')),
                ('description', models.TextField(verbose_name='Résumé de description')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('animateurs', models.ManyToManyField(related_name='masterclasses', to='core.animateur')),
            ],
            options={
                'verbose_name': 'MasterClass',
                'verbose_name_plural': 'MasterClasses',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageMasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masterclass/images/')),
                ('legende', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.masterclass')),
            ],
            options={
                'verbose_name': 'Image MasterClass',
                'verbose_name_plural': 'Images MasterClass',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='VideoMasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL YouTube ou autre plateforme (optionnel)')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='masterclass/videos/')),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.masterclass')),
            ],
            options={
                'verbose_name': 'Vidéo MasterClass',
                'verbose_name_plural': 'Vidéos MasterClass',
                'ordering': ['ordre'],
            },
        ),
    ]
