# Generated by Django 5.0 on 2025-07-14 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_animateur_masterclass_imagemasterclass_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('anonyme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('question', 'Question'), ('sondage', 'Sondage'), ('nuage', 'Nuage de mots'), ('quiz', 'Quiz')], default='question', max_length=10)),
                ('statut', models.CharField(choices=[('attente', 'En attente de modération'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='attente', max_length=10)),
                ('votes_positifs', models.PositiveIntegerField(default=0)),
                ('est_repondue', models.BooleanField(default=False)),
                ('est_epinglee', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_posees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-votes_positifs', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OptionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(limit_choices_to={'type': 'sondage'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correcte', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(limit_choices_to={'type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_quiz', to='core.question')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SessionInteractive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
                ('est_moderee', models.BooleanField(default=False, help_text="Si activé, les questions doivent être approuvées avant d'être visibles")),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.sessioninteractive'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'utilisateur')},
            },
        ),
    ]
